
package com.adv.videodb.enumeradores;


public enum Cpc {
    MERCADO_DE_LA_CIUDAD,
    JARDIN,
    CENTRO_AMERICA,
    GUINIAZU,
    PUEYRREDON,
    VILLA_LIBERTADOR,
    RUTA_20,
    RANCAGUA,
    MERCANTIL,
    MONSENIOR_PABLO_CABRERA,
    COLON,
    ARGUELLO,
    SAN_VICENTE,
    EMPALME,
    CHALET_SAN_FELIPE,
    CAPDEVILLA;
}
